<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="22994" started-at="2015-10-14T12:14:29Z" finished-at="2015-10-14T12:14:52Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="22994" started-at="2015-10-14T12:14:29Z" finished-at="2015-10-14T12:14:52Z">
      <class name="Tests">
        <test-method status="PASS" signature="startFirefox()[pri:0, instance:Tests@880ec60]" name="startFirefox" is-config="true" duration-ms="9522" started-at="2015-10-14T15:14:29Z" finished-at="2015-10-14T15:14:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startFirefox -->
        <test-method status="FAIL" signature="CreateSpecificAccountTest()[pri:0, instance:Tests@880ec60]" name="CreateSpecificAccountTest" duration-ms="13065" started-at="2015-10-14T15:14:38Z" finished-at="2015-10-14T15:14:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[verificarcreareaccont expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: verificarcreareaccont expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:288)
	at Tests.CreateSpecificAccountTest(Tests.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateSpecificAccountTest -->
        <test-method status="PASS" signature="closeFirefox(org.testng.ITestResult)[pri:0, instance:Tests@880ec60]" name="closeFirefox" is-config="true" duration-ms="387" started-at="2015-10-14T15:14:51Z" finished-at="2015-10-14T15:14:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=CreateSpecificAccountTest status=FAILURE method=Tests.CreateSpecificAccountTest()[pri:0, instance:Tests@880ec60] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeFirefox -->
      </class> <!-- Tests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
